"Geo Data Science with Python" 
### Notebook Lesson 7a

# Matrix and Vector Operations

This lesson discusses how to perform matrix and vector operations with NumPy in Python.

### Sources
This notebook is contains information from the following resources:
- Goodfellow, Bengio, & Courville. (2016). Deep Learning. MIT Press. Retrieved from www.deeplearningbook.org
- Numpy lecture number 4, from DataScience Lectures By Dr Paul Gader, University of Florida
- Numpy references: https://numpy.org/devdocs/user/index.html
- https://numpy.org/devdocs/user/numpy-for-matlab-users.html#array-or-matrix-which-should-i-use


In [3]:
import numpy as np

## Definitions

### Definition of scalar

In [34]:
scalar = 3
#scalar = np.array([3])  # scalar as 1x1 array
scalar

### Definition of vector

In [22]:
# Definition of vector:
vectorCol = np.array([[1],[2],[3]]) # column vector
vectorCol

array([[1],
       [2],
       [3]])

In [51]:
vectorRow = np.array([[1,2,3]])     # row vector
vectorRow

array([[1, 2, 3]])

### Shape of a vector & special vectors

In [21]:
# shape of vector : (numRow, 1)
vector.shape

(1, 3)

In [48]:
# 0-vectors
zeroVector = np.zeros((3,1))
zeroVector

array([[0.],
       [0.],
       [0.]])

In [47]:
# 1-vectors
oneVector = np.ones((3,1))
oneVector

array([[1.],
       [1.],
       [1.]])

### Definition of Matrix

In [88]:
# Definition of matrix:
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])

In [39]:
# Matrix shape:
matrix.shape
# shape of matrix : (numRow, numCol)

(2, 3)

### Definition of Tensor

In [18]:
# Definition of matrix:
tensor = np.array([[[1, 2, 3], 
                    [4, 5, 6]  ],
                   [[7, 8, 9], 
                    [9, 8, 7]  ] ])

In [19]:
tensor.shape

(2, 2, 3)

## Matrix & Vector Operations

### Matrix & Vector Transpose

In [14]:
# Matrix transpose
matrix.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [49]:
matrix.T.shape

(3, 4)

In [53]:
# Vector transpose
vector = np.array([[1,2,3]]) # row vector
vector.T                     # column vector

array([[1],
       [2],
       [3]])

### Scalar Multiplication, Vector and Matrix Addition

In [59]:
scalar

array([3])

In [73]:
vector

array([[1, 2, 3]])

In [74]:
# scalar multiplication
vector*scalar

array([[3, 6, 9]])

In [80]:
# scalar addition
vector + scalar

array([[4, 5, 6]])

In [81]:
# vector operations
vector + vector

array([[2, 4, 6]])

In [82]:
vector - vector

array([[0, 0, 0]])

In [89]:
# matrix and scalar multiplication
matrix * scalar

array([[ 3,  6,  9],
       [12, 15, 18]])

In [91]:
# matrix addition
matrix + matrix

array([[ 2,  4,  6],
       [ 8, 10, 12]])

### Matrix Multiplication

In [102]:
# Matrix Multiplication according to Linear Algebra
#  available since Python 3.5
matrix.T @ matrix

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [103]:
# Matrix Multiplication according to Linear Algebra (alternative)
np.dot(matrix.T,matrix)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

### Dot product / Inner product

In [242]:
vectorCol

array([[1],
       [2],
       [3]])

In [243]:
# Vector inner product (= spatial length of the vector)
vectorCol.T @ vectorCol

array([[14]])

### Element-by-element Operations

In [95]:
# element by element multiplication (Hadamard product)
np.multiply(matrix,matrix)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [94]:
# element by element multiplication (alternative)
matrix*matrix

array([[ 1,  4,  9],
       [16, 25, 36]])

In [112]:
# same for vectors
vector * vector == np.multiply(vector,vector)

array([[ True,  True,  True]])

In [113]:
# same rules for column vectors
vector.T * vector.T == np.multiply(vector.T,vector.T)

array([[ True],
       [ True],
       [ True]])

### Vectorization of numpy array operations

Numpy operations are designed for fast data processing. Numpy operators support vectorization, which makes the computation much faster than if we would process the arrays with for-loops.

Arithmetic operators implemented in NumPy are:
- `+` or `np.add` for addition
- `-` or `np.substract` for substraction
- `-` or `np.negative` for unary negation
- `*` or `np.multiply` for multiplication
- `/` or `np.divide` for division
- `//` or `np.floor_divide()` for floor division
- `**` or `np.power()` for exponentiation
- `%` or `np.mod()` for modulus/remainder

Others: `np.abs`, `np.sin()`, `np.exp()`, `np.log()`, etc.


### Tutorial 1

Below, a big array of length 1000 is filled with random numbers.

In [226]:
bigArray = np.random.randint(1, 100, size=10000) 
bigArray.shape

(10000,)

Apply any arithmetic operator to this vector in two ways:
1. Write a function that uses a for loop, iterating through the vector and calculating the operation and saving the output to a variable
2. Using NumPy vectorized operator for the same operation (example from previous table)

Use the magic command `%timeit` to measure the execution time and compare them for both ways.

In [ ]:
# add your code


In [227]:

# see a solution below

### Tutorial 2

Now, measure the runtime for matrix multiplication numpy (linear algepra multiplication) and compare it to that of an algorithm using for-loops. For that, find code for algorithm using for-loops in the function `matrixMultiplication`, given in the script `matrixMultiplication.py`. The script also defines two test matrices A and B.

What is the runtime for the loop-algorithm compared to numpy multiplication of the two matrices A and B?

Explain why the calculation of one algorithm is faster than the other one!

### NumPy Matrix
Matrix data type in numpy is available as alternative currently, but it be deprecated eventually.

In [191]:
# matrix class of numpy is a subclass of ndarray
npMatrix = np.matrix('1 2 3; 4 5 6')
npMatrix

matrix([[1, 2, 3],
        [4, 5, 6]])

In [192]:
type(npMatrix)

numpy.matrix

More details in the references: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html

And a discussion on when to use array versus matrix: https://numpy.org/devdocs/user/numpy-for-matlab-users.html#array-or-matrix-which-should-i-use

## Rules of Broadcasting
Let's get continue with NumPy arrays. 
When combining arrays of different sizes for matrix summation, substraction and element-by matrix multipliation with `*` or `np.multiply()`, rules of broadcasting will be applied.

**Rule 1**: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.

**Rule 2**: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.

**Rule 3**: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

These rules apply, for example, when multiplying or adding a scalar to a vector or a matrix.

In [188]:
matrix = np.array([  [1, 2, 3],
                     [4, 5, 6]   ])
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [151]:
vector = np.array([  [10, 10, 10]  ])
vector

array([[10, 10, 10]])

In [152]:
scalar = np.array([100]) 
scalar

array([100])

In [153]:
matrix + scalar

array([[101, 102, 103],
       [104, 105, 106]])

In [154]:
vector + scalar

array([[110, 110, 110]])

These rules also apply, when multiply or sum a vector to a matrix.

In [155]:
matrix + vector

array([[11, 12, 13],
       [14, 15, 16]])

### Special Matrices

Let's get continue with NumPy arrays and define some special matrices with them.

In [215]:
# Diagonal matrix
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [179]:
# Identity matrix
np.identity(10)
# or
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [245]:
# Inverse matrix
# We will talk about this in a future class,
# as matrix inversion requires sophisticated operations
# np.linalg.inv works only for square matrices
A = np.array([[1, 2, 3], [1, 3, 3], [1, 2, 4]])
Ainv = np.linalg.inv(A)
Ainv

array([[ 6., -2., -3.],
       [-1.,  1.,  0.],
       [-1.,  0.,  1.]])

In [246]:
# A*A^-1 = I
A @Ainv

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Linear System of Equations

Linear equations like:

- $A_{11} x_1 + A_{12} x_2 + A_{13} x_3 = b_1$
- $A_{21} x_1 + A_{22} x_2 + A_{23} x_3 = b_2$
- $A_{31} x_1 + A_{32} x_2 + A_{33} x_3 = b_3$

... can be written in the form Ax = b.

In [248]:
# We can store the equation system in the matrix A, for example:
A = np.array([[1, 2, 3], [1, 3, 3], [1, 2, 4]])
A

array([[1, 2, 3],
       [1, 3, 3],
       [1, 2, 4]])

In [249]:
# Assume we have a set of parameter (independent variables),
# these are stored in the vector x:
x = np.array([[2,4,1]]).T

In [256]:
# The dependent variables can then be calculated and stored in the vector b:
b = A@x
b


array([[13],
       [17],
       [14]])

Our equation system looks like this:

- $x_1 + 2 x_2 + 3 x_3 = 13$
- $x_1 + 3 x_2 + 3 x_3 = 17$
- $x_1 + 2 x_2 + 4 x_3 = 14$

Now assume, **b** are observations, and **A** contains a geophysical model connecting model parameter **x** to observations **b**. We can then solve for x with the equation: $x = A^{-1}b$

In [251]:
# An inversion of the matrix A
Ainv = np.linalg.inv(A)

In [255]:
# ... can be used to calculate a solution of x, if we have b given:
x_calculated = Ainv@b
x_calculated

array([[2.],
       [4.],
       [1.]])

As you can see, the results for `x_calculated` are equal to the originally given parameter x above.

### Tutorial 3

Solve the equation system:

$ 3x_1 + 2x_2 + 4x_3 = 25$

$  x_1 +  x_2 + 2x_3 = 11$
   
$10x_1 +  x_2 +  x_3 = 37$
   

In [213]:
# put your code here


In [214]:

# Solution is provided at the bottom

### Agregation

Functions that aggregate dataset to a statistical or other value are called aggregations. We have discussed several functions during the class about numpy arrays and used several of them during the exercises.

In [131]:
# Examples:
# np.min(), np.max(), np.median(), 
# np.std(), np.sum(), np.mean(), ...

---
# Solutions
## Tutorial 1

In [237]:
bigArray = np.random.randint(1, 100, size=10000) 
bigArray.shape

(10000,)

In [223]:
"""
Vectorization is much faster than for loop. 
"""

def computeReciprocal(values): 
    output = np.empty(len(values)) 
    for i in range(len(values)):
        output[i] = 1.0 / values[i] 
    return output

# run to see average execution time of for loop
# time scale : milliseconds
%timeit forLoopReciprocal = computeReciprocal(bigArray)

18.4 ms ± 138 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [222]:
%timeit vectorizedReciprocal = (1.0 / bigArray)

21.9 µs ± 294 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


## Tutorial 3

In [209]:
b = np.array([[25,23,10]]).T

In [210]:
A = np.array([
    [3,2,4],
    [1,3,2],
    [1,1,1]
])

In [211]:
x = np.linalg.inv(A) @ b

In [212]:
x

array([[3.],
       [6.],
       [1.]])